version: 0.0
os: linux
files:
   - source: /
     destination: /home/ec2-user/filacode
permissions:
  - object: /
    pattern: "**"
    owner: kimjans
    group: kimjans
hooks:
  AfterInstall:
    - location: script/start.sh
      timeout: 1200
      runas: kimjans